services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  web:
    build: .
    image: todocicd:latest
    env_file:
      - .env
    command: /bin/bash -c "chmod +x ./scripts/entrypoint.sh && ./scripts/entrypoint.sh"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /var/lib/jenkins/workspace/TodoCICD/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
      - /var/lib/jenkins/workspace/TodoCICD/logs:/var/log/nginx
    ports:
      - "8001:8001"
    depends_on:
      - web

volumes:
  db_data:
