apiVersion: apps/v1
kind: Deployment
metadata:
  name: todocicd-deploy
  labels:
    app: todoapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapp

  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: todocicdapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1