apiVersion: v1
kind: Service
metadata:
  name: todocicd-service
  labels:
    app: todoapp
spec:
  selector:
    app: todoapp
    tier: cicdapp
  ports:
    - port: 8000
      # targetPort: 8001
  type: LoadBalancer

---

# Volume for todo app
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-volume
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


